--- #YAML:1.0
name:               XML-LibXML-LazyMatcher
version:            0.01
abstract:           The great new XML::LibXML::LazyMatcher!
author:
    - Toru Hisai <toru@torus.jp>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:   0
    XML::LibXML:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
