---
abstract: 'A simple XML matcher with lazy evaluation.'
author:
  - 'Toru Hisai <toru@torus.jp>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-LibXML-LazyMatcher
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  XML::LibXML: 0
version: 0.02
